// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijtgnadrxgeonhapuanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdGduYWRyeGdlb25oYXB1YW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzk5MzgsImV4cCI6MjA2MDc1NTkzOH0.dIWH0MKFNw3ax1Olf-qlXj_G-sOXKsCm_B1P7JS2YLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);